package com.paymentx.payment.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.util.UUID;

/**
 * The aggregate root of this service. See Money.java, PaymentScheme.java,
 * and this class's field-level comments for the reasoning behind each
 * modeling choice.
 */
@Entity
@Table(name = "payment")
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
/**
 * ====================================================================
 * ENGLISH
 * --------------------------------------------------------------------
 * Payment is a JPA entity in the payment module of PaymentX. It lives in package com.paymentx.payment.entity and participates in payment's internal request/data flow, used by other classes in this module (and, where applicable, consumed indirectly by other PaymentX services through payment's REST API or Kafka events).
 *
 * ====================================================================
 * HINGLISH
 * --------------------------------------------------------------------
 * Payment PaymentX ke payment module ka ek JPA entity hai. Ye com.paymentx.payment.entity package me hai aur payment ke internal request/data flow ka hissa hai, isi module ki dusri classes ise use karti hain (aur jahan applicable ho, dusri PaymentX services ise payment ke REST API ya Kafka events ke through indirectly use karti hain).
 * ====================================================================
 */
public class Payment extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "payment_reference", nullable = false, unique = true, length = 128)
    private String paymentReference;

    @Column(name = "idempotency_key", nullable = false, unique = true, length = 128)
    private String idempotencyKey;

    /**
     * traceId: the end-to-end business transaction identifier, propagated
     * unchanged across every service hop and Kafka message for this
     * payment's entire lifecycle - set once at Validation Service, never
     * regenerated.
     *
     * correlationId: generated by the API Gateway, identifies a single
     * HTTP request/hop. traceId answers "show me everything that ever
     * happened to this payment across every service"; correlationId
     * answers "show me everything that happened during this ONE request."
     * Both are needed for different debugging questions.
     */
    @Column(name = "trace_id", nullable = false, length = 64)
    private String traceId;

    @Column(name = "correlation_id", nullable = false, length = 64)
    private String correlationId;

    @Enumerated(EnumType.STRING)
    @Column(name = "scheme", nullable = false, length = 32)
    private PaymentScheme scheme;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_type", nullable = false, length = 16)
    private PaymentType paymentType;

    @Enumerated(EnumType.STRING)
    @Column(name = "channel", nullable = false, length = 16)
    private PaymentChannel channel;

    @Embedded
    private Money amount;

    @Column(name = "debtor_account", nullable = false, length = 64)
    private String debtorAccount;

    @Column(name = "debtor_participant_id", nullable = false, length = 32)
    private String debtorParticipantId;

    @Column(name = "creditor_account", nullable = false, length = 64)
    private String creditorAccount;

    @Column(name = "creditor_participant_id", nullable = false, length = 32)
    private String creditorParticipantId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PaymentStatus status;

    @Column(name = "failure_reason", length = 512)
    private String failureReason;
}
