package com.paymentx.reporting.entity;

import com.paymentx.common.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.util.UUID;

/**
 * ====================================================================
 * ENGLISH:
 * The actual generated report DATA - the rows/aggregates a
 * ReportGenerator produced, stored as JSON. WHY BaseEntity (id only),
 * not AuditableEntity: this is an immutable computed snapshot the
 * instant it's generated, the same reasoning as Reconciliation
 * Service's ReconciliationSummary - it never gets independently edited,
 * only regenerated by re-running the report. WHY JSON, not one column
 * per report field: 11 different report types each have a completely
 * different result shape - a fixed relational schema would need 11
 * different tables. This one flexible column serves every report type,
 * and ReportExporter implementations read this JSON to produce the
 * actual CSV/XLSX/PDF/JSON file.
 *
 * HINGLISH:
 * Ye actual generated report ka DATA hai - wo rows/aggregates jo
 * ReportGenerator ne banaye, JSON ke roop me store hote hain. WHY
 * BaseEntity (sirf id), AuditableEntity nahi: ye ek immutable computed
 * snapshot hai jaise hi generate hota hai - ye kabhi independently edit
 * nahi hota, sirf report dobara chalane se regenerate hota hai. WHY
 * JSON, har report-field ke liye alag column nahi: 11 alag report
 * types ka result shape bilkul alag hota hai - fixed relational schema
 * ko 11 alag tables chahiye hote. Ye ek flexible column har report
 * type ke liye kaam karta hai, aur ReportExporter implementations ye
 * JSON padh ke actual CSV/XLSX/PDF/JSON file banate hain.
 * ====================================================================
 */
@Entity
@Table(name = "report_result")
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class ReportResult extends BaseEntity {

    @Column(name = "report_execution_id", nullable = false, unique = true)
    private UUID reportExecutionId;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "result_data", columnDefinition = "jsonb")
    private String resultData;
}
