package com.paymentx.reconciliation.entity;

import com.paymentx.common.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * WHY BaseEntity (id only), not AuditableEntity: like DeliveryAttempt in
 * Notification Service, this is a computed, immutable snapshot the
 * instant it's generated - it never gets independently edited after the
 * fact, only regenerated by running the batch again.
 */
@Entity
@Table(name = "reconciliation_summary")
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
/**
 * ====================================================================
 * ENGLISH
 * --------------------------------------------------------------------
 * ReconciliationSummary is a JPA entity in the reconciliation module of PaymentX. It lives in package com.paymentx.reconciliation.entity and participates in reconciliation's internal request/data flow, used by other classes in this module (and, where applicable, consumed indirectly by other PaymentX services through reconciliation's REST API or Kafka events).
 *
 * ====================================================================
 * HINGLISH
 * --------------------------------------------------------------------
 * ReconciliationSummary PaymentX ke reconciliation module ka ek JPA entity hai. Ye com.paymentx.reconciliation.entity package me hai aur reconciliation ke internal request/data flow ka hissa hai, isi module ki dusri classes ise use karti hain (aur jahan applicable ho, dusri PaymentX services ise reconciliation ke REST API ya Kafka events ke through indirectly use karti hain).
 * ====================================================================
 */
public class ReconciliationSummary extends BaseEntity {

    @Column(name = "batch_id", nullable = false, unique = true)
    private UUID batchId;

    @Column(name = "total_records", nullable = false)
    private Integer totalRecords;

    @Column(name = "matched_count", nullable = false)
    private Integer matchedCount;

    @Column(name = "missing_count", nullable = false)
    private Integer missingCount;

    @Column(name = "duplicate_count", nullable = false)
    private Integer duplicateCount;

    @Column(name = "amount_mismatch_count", nullable = false)
    private Integer amountMismatchCount;

    @Column(name = "currency_mismatch_count", nullable = false)
    private Integer currencyMismatchCount;

    @Column(name = "status_mismatch_count", nullable = false)
    private Integer statusMismatchCount;

    @Column(name = "settlement_delay_count", nullable = false)
    private Integer settlementDelayCount;

    @Column(name = "late_settlement_count", nullable = false)
    private Integer lateSettlementCount;

    @Column(name = "orphan_count", nullable = false)
    private Integer orphanCount;

    @Column(name = "unexpected_settlement_count", nullable = false)
    private Integer unexpectedSettlementCount;

    @Column(name = "generated_at", nullable = false)
    private OffsetDateTime generatedAt;
}
